app:

  # Max rows for one PROCESS read the file into memories each time
  # useful when we meet a bigTwitter.json but there are only 2 process
  upper-bound-rows-per-iteration: 10000

  # how many rows one THREAD will process for calculation
  step: 100

  # decide to run which input file, 0-tiny, 1-small, 2-big
  input-twitter-type: 1

  # important file paths
#  grid-path: E:\projects\COMP90024_Assignment_1\sample\sydGrid.json
  grid-path: /data/projects/COMP90024/sydGrid.json
  # grid-path: /home/yuan/CCCCOMP90024/COMP90024_Assignment_1/sample/sydGrid.json

#  tiny-twitter-path: E:\projects\COMP90024_Assignment_1\sample\tinyTwitter.json
  tiny-twitter-path: /data/projects/COMP90024/tinyTwitter.json
  # tiny-twitter-path: /home/yuan/CCCCOMP90024/COMP90024_Assignment_1/sample/tinyTwitter.json

#  small-twitter-path: E:\projects\COMP90024_Assignment_1\sample\smallTwitter.json
  small-twitter-path: //data/projects/COMP90024/smallTwitter.json

  # small-twitter-path: /home/yuan/CCCCOMP90024/COMP90024_Assignment_1/sample/smallTwitter.json

#  big-twitter-path: E:\projects\COMP90024_Assignment_1\sample\bigTwitter.json
  big-twitter-path: /data/projects/COMP90024/bigTwitter.json

  # grid matrix information
  grid-rows: 4
  grid-columns: 4

  thread-pool:
    size: 8
